server:
  port: 9296

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      name: admin
      password: ${CONFIG_SERVICE_PASSWORD}